package io.github.webtransport4j.cluster;

import java.util.List;
import org.jspecify.annotations.NonNull;

/**
 * Provider SPI for QUIC stateless retry and connection migration token secrets.
 *
 * <p>In multi-node WebTransport clusters behind an Anycast or L4 load balancer (e.g. Maglev,
 * AWS NLB, or Envoy UDP), a client may send its initial handshake or migrated packet to Node A
 * and a subsequent packet to Node B. This provider supplies shared cryptographic secrets across
 * the cluster to ensure tokens generated by any node can be validated by peer nodes.
 *
 * <p>Also supports zero-downtime secret rotation by returning both the active signing secret
 * and valid historical secrets.
 */
public interface StatelessTokenSecretProvider {

  /**
   * Returns the current active secret used to sign newly issued QUIC tokens.
   *
   * @return active secret bytes (minimum 16 bytes, recommended 32 bytes)
   */
  byte @NonNull [] getActiveSecret();

  /**
   * Returns all secrets valid for token verification, including the active secret and
   * any recently rotated historical secrets within their retention window.
   *
   * @return unmodifiable list of valid secret byte arrays
   */
  @NonNull List<byte[]> getValidationSecrets();
}
